### PR TITLE
Update from upstream - commit 8ba882e

### PR DESCRIPTION
**Pull request by TalfinApiiro**
Includes up until commit [8ba882e](https://github.com/octokit/octokit.net/commit/8ba882e98d4dca6ce893d3ac3b5684b25cbe8a53)

### CODE REVIEW

**Comment by TalfinApiiro** [comment]
I recommend going over the merge commit and the one after that

**Comment by TalfinApiiro** [comment]
Also, the CI build that's on windows-latest (part of their testing suite) is failing on linq pad tests, because it has some DLL confusion, not because the tests don't pass.
Feel free to ignore it.

**Comment by efratas** [comment]
can you add some description as for what benefits does it bring ?

**Comment by TalfinApiiro** [comment]
> can you add some description as for what benefits does it bring ? maybe like a release file ?

Basically we strayed far from the original fork, so this updates our version with all of their changes.
It includes adherence to all new REST API changes since 2020, as well as a few specific features we wanted.
The specific feature we wanted is the `CachingHttpClient` which allows us to cache responses and attempt to save on rate limit.

**Comment by tomer-amir** [comment]
Did you try to use a built version of this with LIM/GH service?

**Comment by TalfinApiiro** [comment]
> Did you try to use a built version of this with LIM/GH service?

Yes, I have tested this with my local lim environment.
I haven't tried testing the github service.

**Review by ravyolii — APPROVED** [review]

**Pull request merged**
